---
save_images: false
detailed_stats: false
dataset: /local/mnist.pkl.gz
pickled: true
random_seed: 42
L1_reg: 0.0
L2_reg: 0.0
n_epochs: 20
pretraining: !!null 
pretraining_passes: 5
training_method: normal
batch_size: 128
output_layer_options: { batch_normalization: true }
shuffle_dataset: true
cost_function: !NegLogLikelihood { }
learning_rate: !MultiplicativeDecayLearningRate { start: 1.0e-3, stop: 1.0e-7, multiplier: 0.85 }
update_rule: !Adam { }
n_hidden: [
            ['convfilter', [
                [1,28,28],
                [128,3,3],
                0.0,
                'c1',
                !ReLU { },
                !GlorotWeightInit { },
                'valid',
                { batch_normalization: true }
            ]],
            ['convfilter', [
                !!null ,
                [128,3,3],
                0.0,
                'c2',
                !ReLU { },
                !GlorotWeightInit { },
                'valid',
                { batch_normalization: true }
            ]],
            ['mlpconv' [ 128, 0., 'mlpconv1']],
            ['convfilter', [
                !!null ,
                [192,3,3],
                0.0,
                'c3',
                !ReLU { },
                !GlorotWeightInit { },
                'valid',
                { batch_normalization: true }
            ]],
            ['convfilter', [
                !!null ,
                [192,3,3],
                0.0,
                'c4',
                !ReLU { },
                !GlorotWeightInit { },
                'valid',
                { batch_normalization: true }
            ]],
            ['mlpconv' [ 192, 0., 'mlpconv2']],
            ['convfilter', [
                !!null ,
                [256,3,3],
                0.0,
                'c5',
                !ReLU { },
                !GlorotWeightInit { },
                'valid',
                { batch_normalization: true }
            ]],
            ['convfilter', [
                !!null ,
                [256,3,3],
                0.0,
                'c6',
                !ReLU { },
                !GlorotWeightInit { },
                'valid',
                { batch_normalization: true }
            ]],
            ['mlpconv' [ 256, 0., 'mlpconv3']],
            ['mlpconv' [ 10, 0., 'mlpconv4']]
          ]
n_in: 784
n_out: 10

resample_size: 50000
method: !AdaBoostM1 {}
ensemble_size: 10
