---
save_images: false
detailed_stats: false
dataset: /local/mnist.pkl.gz
pickled: true
random_seed: 42
L1_reg: 0.0
L2_reg: 0.0001
n_epochs: 20
pretraining: !!null 
pretraining_passes: 5
training_method: normal
batch_size: 128
output_layer_options: { batch_normalization: true }
cost_function: !NegLogLikelihood { }
learning_rate: !MultiplicativeDecayLearningRate { start: 1.0e-3, stop: 1.0e-7, multiplier: 0.9 }
update_rule: !Adam { }
n_hidden: [
            ['convfilter', [
                [1,28,28],
                [96,5,5],
                0.0,
                'c1',
                !ReLU { },
                !GaussianWeightInit { std: 0.01 },
                'same',
                { batch_normalization: true , pad: [2,2] }
            ]],
            ['mlpconv', [ 64, 0., 'mlpconv1a']],
            ['mlpconv', [ 48, 0., 'mlpconv1b']],
            ['pool2d', ['max', [3,3], 'pool1' , { strides: [2,2] } ]],
            ['linear', [ 0.5, 'dropout1' ]],

            ['convfilter', [
                !!null ,
                [128,5,5],
                0.0,
                'c2',
                !ReLU { },
                !GaussianWeightInit { std: 0.01 },
                'same',
                { batch_normalization: true , pad: [2,2] }
            ]],
            ['mlpconv', [ 96, 0., 'mlpconv2a']],
            ['mlpconv', [ 48, 0., 'mlpconv2b']],
            ['pool2d', ['max', [3,3], 'pool2', { strides: [2,2] } ]],
            ['linear', [ 0.5, 'dropout2' ]],

            ['convfilter', [
                !!null ,
                [128,5,5],
                0.0,
                'c3',
                !ReLU { },
                !GaussianWeightInit { std: 0.01 },
                'valid',
                { batch_normalization: true , pad: [2,2] }
            ]],
            ['mlpconv', [ 96, 0., 'mlpconv3a']],
            ['mlpconv', [ 10, 0., 'mlpconv3b']],
            ['global_pooling', ['average']]
          ]
n_in: 784
n_out: 10

resample_size: 50000
method: !DIB {
    n_epochs_after_first: 10 ,
    grow_forward: true,
    incremental_index: 5,
    incremental_layer: ['convfilter', [
                            !!null ,
                            [64,5,5],
                            0.0,
                            'c_add',
                            !ReLU { },
                            !GaussianWeightInit { std: 0.01 },
                            'same',
                            { batch_normalization: true }

                        ]],
}
ensemble_size: 5
