---
save_images: false
detailed_stats: false
dataset: /local/cifar10-augmented/
pickled: false
L1_reg: 0.0
L2_reg: 0.0
n_epochs: 200
pretraining: !!null
pretraining_passes: 2
training_method: normal
#update_rule: !RProp {eta_minus: 0.5, eta_plus: 1.2, max_delta: 1.0e-1, min_delta: 1.0e-4} 
#update_rule: !DRProp {eta_minus: 0.5, eta_plus: 1.2, max_delta: 1.0e-3,
#                      start_min_delta: 1.0e-4, stop_min_delta: 1.0e-7,
#                      multiplier_min_delta: 0.75,
#                      momentum: 0., momentum_decay: 0.}
update_rule: !SGD { momentum: 0.3 }
learning_rate: !MultiplicativeDecayLearningRate { start: 1.0e-1, stop: 1.0e-3, multiplier: 0.9 }
batch_size: 128
cost_function: !CrossEntropy { }
n_hidden: [
            #['elastic_transform',
            #    { alpha: 20.0 , beta: 7.5 , gamma: 20.0 ,
            #        sigma: 5 , pflip: 0. , translation: 1 ,
            #        bilinear: false
            #    }
            #],
            #['rnorm1',[9,False]],
            #['dropout', [3072, 0., 'd1', !!null , !!null ]], 
            #input_shape,filter_shape,pool_size,drop_this,name_this,activation_this
            #input_shape needs to be defined only for 1st layer
            #input_shape:  [levels,x,y]
            #filter_shape: [count,x,y]
            #pool_size: [x,y]
            ['conv', [
                [3,32,32],
                [64,2,2],
                [2,2],
                0.,
                'c1',
                !TanH { },
                'max',
                !GlorotWeightInit { }
            ]],
            ['conv', [
                !!null ,
                [128,4,4],
                [2,2],
                0.,
                'c2',
                !TanH { },
                'max',
                !GlorotWeightInit { }
            ]],
#            ['rnorm1',[9,False]],
            ['conv', [
                !!null ,
                [256,5,5],
                [2,2],
                0.,
                'c3',
                !TanH { },
                'max',
                !GlorotWeightInit { }
            ]],
#            ['rnorm1',[9,False]],
            ['flat', [4096, 0.5, 'f1', !ReLU { }, !GlorotWeightInit { } ]],
            ['flat', [4096, 0.5, 'f2', !ReLU { }, !GlorotWeightInit { } ]]
          ]
n_in: 3072
RGB: True
n_out: 10

#Ensemble params
resample_size: 40000
method: !Bagging {}
ensemble_size: 10
