---
save_images: false
detailed_stats: false
dataset: /local/mnist.pkl.gz
pickled: true
#online_transform: { alpha: 20.0 , beta: 7.5 , gamma: 20.0 ,
#                    sigma: 5 , pflip: 0. , translation: 1 ,
#                    bilinear: false }
resize_data_to: 29
L1_reg: 0.0
L2_reg: 0.0
n_epochs: 650
join_train_and_valid: true
pretraining: !!null
pretraining_passes: 2
training_method: normal
learning_rate: !MultiplicativeDecayLearningRate { start: 0.1, stop: 1.0e-5, multiplier: 0.99 }
update_rule: !SGD { momentum: 0.5 }
batch_size: 128
cost_function: !NegLogLikelihood { }
n_hidden: [
            ['elastic_transform',
                { alpha: 20.0 , beta: 7.5 , gamma: 20.0 ,
                    sigma: 5 , pflip: 0. , translation: 1 ,
                    bilinear: false
                }
            ],
            ['conv', [
                [1,29,29],
                [64,5,5],
                [2,2],
                0.0,
                'c1',
                !ReLU { },
                'max',
                !GlorotWeightInit { }
            ]],
            ['conv', [
                !!null ,
                [128,5,5],
                [2,2],
                0.0,
                'c2',
                !ReLU { },
                'max',
                !GlorotWeightInit { }
            ]],
            ['flat', [1024, 0.5, 'f1', !ReLU { }, !GlorotWeightInit { }]],
            ['flat', [1024, 0.5, 'f2', !ReLU { }, !GlorotWeightInit { }]]
          ]
n_in: 841
n_out: 10

#Saving to mongodb
#results_db: amosca02
#results_table: reverse_pretraining
#results_host: 193.61.36.31
