---
save_images: false
detailed_stats: false
dataset: /local/cifar10/
pickled: false
L1_reg: 0.0
L2_reg: 0.0
n_epochs: 1000
pretraining: !!null
pretraining_passes: 2
training_method: normal
#update_rule: !RProp {eta_minus: 0.5, eta_plus: 1.2, max_delta: 50, min_delta: 0.001} 
update_rule: !SGD { momentum: 0.3 }
learning_rate: !MultiplicativeDecayLearningRate { start: 0.1, stop: 1.0e-6, multiplier: 0.9 }
batch_size: 100
cost_function: !CrossEntropy { }
n_hidden: [
            #['dropout', [3072, 0., 'd1', !!null , !!null ]], 
            #input_shape,filter_shape,pool_size,drop_this,name_this,activation_this
            #input_shape needs to be defined only for 1st layer
            #input_shape:  [levels,x,y]
            #filter_shape: [count,x,y]
            #pool_size: [x,y]
            ['conv', [
                [3,32,32],
                [128,2,2],
                [2,2],
                0.,
                'c1',
                !TanH { },
                'max',
                !GlorotWeightInit { }
            ]],
            ['conv', [
                !!null ,
                [200,4,4],
                [2,2],
                0.,
                'c2',
                !TanH { },
                'max',
                !GlorotWeightInit { }
            ]],
            ['conv', [
                !!null ,
                [200,5,5],
                [2,2],
                0.,
                'c3',
                !TanH { },
                'max',
                !GlorotWeightInit { }
            ]],
            ['flat', [1024, 0.5, 'f1', !ReLU { }, !GlorotWeightInit { } ]],
            ['flat', [1024, 0.5, 'f2', !ReLU { }, !GlorotWeightInit { } ]]
          ]
n_in: 3072
n_out: 10
