---
save_images: false
detailed_stats: true
dataset: /local/mnist.pkl.gz
pickled: true
online_transform: { alpha: 5.0 , beta: 7.5 , gamma: 20.0 ,
                    sigma: 5 , pflip: 0. , translation: 0 ,
                    bilinear: false }
resize_data_to: 29
L1_reg: 0.0
L2_reg: 0.0
n_epochs: 2000
pretraining: !!null 
pretraining_passes: 5
training_method: normal
learning_rate: !MultiplicativeDecayLearningRate { start: 1.0e-3, stop: 1.0e-6, multiplier: 0.996 }
update_rule: !SGD { momentum: 0.9, momentum_decay: 0.999 }
batch_size: 100
cost_function: !NegLogLikelihood { }
n_hidden: [
    ['flat',[2500,0.,'h0',!ScaledTanH { A: 1.7159, B: 0.6666 },!UniformWeightInit { min_w: -0.05 , max_w: 0.05 } ]],
    ['flat',[2000,0.,'h1',!ScaledTanH { A: 1.7159, B: 0.6666 },!UniformWeightInit { min_w: -0.05 , max_w: 0.05 } ]],
    ['flat',[1500,0.,'h2',!ScaledTanH { A: 1.7159, B: 0.6666 },!UniformWeightInit { min_w: -0.05 , max_w: 0.05 } ]],
    ['flat',[1000,0.,'h3',!ScaledTanH { A: 1.7159, B: 0.6666 },!UniformWeightInit { min_w: -0.05 , max_w: 0.05 } ]],
    ['flat',[ 500,0.,'h4',!ScaledTanH { A: 1.7159, B: 0.6666 },!UniformWeightInit { min_w: -0.05 , max_w: 0.05 } ]]
          ]
n_in: 841
n_out: 10
