---
save_images: false
detailed_stats: false
dataset: /local/mnist.pkl.gz
pickled: true
online_transform: { alpha: 20.0 , beta: 7.5 , gamma: 20.0 ,
                    sigma: 5 , pflip: 0. , translation: 1 ,
                    bilinear: false }
resize_data_to: 29
L1_reg: 0.0
L2_reg: 0.0
n_epochs: 150
pretraining: !!null 
pretraining_passes: 5
training_method: normal
learning_rate: !MultiplicativeDecayLearningRate { start: 0.1, stop: 1.0e-6, multiplier: 0.99 }
#update_rule: !DRProp {eta_minus: 0.5, eta_plus: 1.1, max_delta: 50,
#                      start_min_delta: 1.0e-2, stop_min_delta: 1.0e-8,
#                      multiplier_min_delta: 0.01, momentum: 0.,
#                      momentum_decay: 0.99}
update_rule: !SGD { momentum: 0.5, renorm: False }
batch_size: 100
cost_function: !NegLogLikelihood { }
n_hidden: [
            ['conv', [
                [1,29,29],
                [32,5,5],
                [2,2],
                0.0,
                'c1',
                !ReLU { },
                'max',
                !GlorotWeightInit { }
            ]],
            ['conv', [
                !!null ,
                [64,5,5],
                [2,2],
                0.0,
                'c2',
                !ReLU { },
                'max',
                !GlorotWeightInit { }
            ]],
            ['flat', [1024, 0.5, 'f1', !ReLU { }, !GlorotWeightInit { }]],
            ['flat', [1024, 0.5, 'f2', !ReLU { }, !GlorotWeightInit { }]]
          ]
n_in: 841
n_out: 10

 
#Ensemble params
resample_size: 60000
method: !Bagging {}
ensemble_size: 30
