---
save_images: false
detailed_stats: false
dataset: /local/mnist.pkl.gz
pickled: true
online_transform: { alpha: 5.0 , beta: 7.5 , gamma: 20.0 ,
                    sigma: 5 , pflip: 0. , translation: 0 ,
                    bilinear: false }
resize_data_to: 29
L1_reg: 0.0
L2_reg: 0.0
n_epochs: 2000
pretraining: !!null 
pretraining_passes: 5
training_method: normal
learning_rate: !MultiplicativeDecayLearningRate { start: 1.0e-3, stop: 1.0e-6, multiplier: 0.996 }
update_rule: !SGD { momentum: 0.5 }
batch_size: 100
cost_function: !NegLogLikelihood { }
n_hidden: [
            ['conv', [
                [1,29,29],
                [32,2,2],
                [2,2],
                0.0,
                'c1',
                !ReLU { },
                'max',
                !GlorotWeightInit { }
            ]],
            ['conv', [
                !!null ,
                [32,4,4],
                [2,2],
                0.0,
                'c2',
                !ReLU { },
                'max',
                !GlorotWeightInit { }
            ]],
            ['conv', [
                !!null ,
                [32,4,4],
                [2,2],
                0.0,
                'c3',
                !ReLU { },
                'max',
                !GlorotWeightInit { }
            ]],
            ['flat', [100, 0.5, 'f1', !ReLU { }, !GlorotWeightInit { }]],
            ['flat', [100, 0.5, 'f2', !ReLU { }, !GlorotWeightInit { }]]
          ]
n_in: 841
n_out: 10
