---
save_images: false
detailed_stats: false
dataset: /local/uci/adult/
pickled: false
random_seed: 42
L1_reg: 0.0
L2_reg: 0.0
n_epochs: 20
training_method: normal
batch_size: 128
#output_layer_options: { batch_normalization: true }
shuffle_dataset: true
cost_function: !CategoricalMSE { }
join_train_and_valid: true
learning_rate: !FixedLearningRate { rate: 1.0e-5 }
update_rule: !Adam { }
n_hidden: [
            ['flat', [128, 0., 'f1', !Sigmoid { }, !GlorotWeightInit { } ]],
            ['flat', [128, 0., 'f1', !Sigmoid { }, !GlorotWeightInit { } ]],
            ['flat', [128, 0., 'f4', !Sigmoid { }, !GlorotWeightInit { } ]]
#, { batch_normalization: true } ]]
          ]
n_in: 14
n_out: 2

resample_size: 32559
method: !Bagging {}
ensemble_size: 3
