---
save_images: false
detailed_stats: false
dataset: /local/uci/covertype/
pickled: false
random_seed: 42
L1_reg: 0.0
L2_reg: 0.0
n_epochs: 100
training_method: normal
batch_size: 1024
#output_layer_options: { batch_normalization: true }
shuffle_dataset: true
cost_function: !NegLogLikelihood { }
learning_rate: !MultiplicativeDecayLearningRate { start: 1.0e-3, stop: 1.0e-7, multiplier: 0.85 }
update_rule: !Adam { }
n_hidden: [
            ['flat', [256, 0.5, 'f2', !ReLU { }, !GlorotWeightInit { } ]],
            ['flat', [256, 0.5, 'f2', !ReLU { }, !GlorotWeightInit { } ]],
            ['flat', [256, 0.5, 'f2', !ReLU { }, !GlorotWeightInit { } ]],
            ['flat', [256, 0.5, 'f2', !ReLU { }, !GlorotWeightInit { } ]],
            ['flat', [256, 0.5, 'f2', !ReLU { }, !GlorotWeightInit { } ]]
#, { batch_normalization: true } ]]
          ]
n_in: 54
n_out: 8

resample_size: 464808
method: !Bagging {}
ensemble_size: 3
