---
save_images: false
detailed_stats: false
dataset: /local/uci/haberman/
pickled: false
random_seed: 42
L1_reg: 0.0
L2_reg: 0.0
n_epochs: 10
training_method: normal
batch_size: 274
center_and_normalise: true
#output_layer_options: { batch_normalization: true }
shuffle_dataset: true
join_train_and_valid: true
cost_function: !CategoricalMSE { }
learning_rate: !FixedLearningRate { rate: 1.0e-5 }
update_rule: !SGD { momentum: 0.9}
n_hidden: [
            ['flat', [128, 0., 'f4', !Sigmoid { }, !GlorotWeightInit { } ]]
#, { batch_normalization: true } ]]
          ]
n_in: 3
n_out: 3

resample_size: 50000
method: !Bagging {}
ensemble_size: 3
