---
save_images: false
detailed_stats: false
dataset: /local/uci/letters/
pickled: false
random_seed: 42
L1_reg: 0.0
L2_reg: 0.0
n_epochs: 100
training_method: normal
batch_size: 128
#output_layer_options: { batch_normalization: true }
shuffle_dataset: true
cost_function: !NegLogLikelihood { }
learning_rate: !MultiplicativeDecayLearningRate { start: 1.0e-1, stop: 1.0e-7, multiplier: 0.95 }
update_rule: !SGD { momentum: 0.9 }
n_hidden: [
            ['flat', [128, 0.5, 'f2', !TanH { }, !GlorotWeightInit { } ]],
            ['flat', [128, 0.5, 'f2', !TanH { }, !GlorotWeightInit { } ]],
            ['flat', [128, 0.5, 'f2', !TanH { }, !GlorotWeightInit { } ]],
            ['flat', [128, 0.5, 'f2', !TanH { }, !GlorotWeightInit { } ]]
#, { batch_normalization: true } ]]
          ]
n_in: 16
n_out: 26

resample_size: 16000
method: !AdaBoostM1 {}
ensemble_size: 3
