---
save_images: False
dataset: /local/cifar10/
pickled: false
L1_reg: 0.0
L2_reg: 0.0
n_epochs: 50
transform: false
learning_rate: 0.001
pretraining: !!null
pretraining_passes: 2
training_method: normal
update_rule: !RProp {eta_minus: 0.5, eta_plus: 1.2, max_delta: 50, min_delta: 0.001} 
#update_rule: !SGD { momentum: 0.9 }
learning_rate: !LinearDecayLearningRate { start: 0.01, stop: 0.0001, steps: 1000 }
batch_size: 100
cost_function: !CrossEntropy { }
n_hidden: [
            #input_shape,filter_shape,pool_size,drop_this,name_this,activation_this
            #input_shape needs to be defined only for 1st layer
            #input_shape:  [levels,x,y]
            #filter_shape: [count,x,y]
            #pool_size: [x,y]
            ['conv', [
                [3,32,32],
                [32,2,2],
                [2,2],
                0.0,
                'c1',
                !ReLU { },
                'max'
            ]],
            ['conv', [
                !!null ,
                [32,4,4],
                [2,2],
                0.0,
                'c2',
                !ReLU { },
                'max'
            ]],
            ['conv', [
                !!null ,
                [32,4,4],
                [2,2],
                0.0,
                'c3',
                !ReLU { },
                'max'
            ]],
            ['flat', [100, 0.5, 'f3', !ReLU { } ]]
          ]
n_in: 3072
n_out: 10
