---
save_images: false
detailed_stats: false
dataset: /local/mnist.pkl.gz
pickled: true
random_seed: 42
online_transform: { alpha: 20.0 , beta: 7.5 , gamma: 20.0 ,
                    sigma: 5 , pflip: 0. , translation: 1 ,
                    bilinear: false }
resize_data_to: 29
L1_reg: 0.0
L2_reg: 0.0
n_epochs: 300
pretraining: !!null 
pretraining_passes: 5
training_method: normal
batch_size: 128
cost_function: !NegLogLikelihood { }
update_inputs: true
learning_rate: !MultiplicativeDecayLearningRate { start: 1.0e-3, stop: 1.0e-7, multiplier: 0.85 }
update_rule: !Adam { }
n_hidden: [
            ['conv', [
                [1,29,29],
                [64,5,5],
                [2,2],
                0.0,
                'c1',
                !ReLU { },
                'max',
                !GlorotWeightInit { }
            ]],
            ['conv', [
                !!null ,
                [128,5,5],
                [2,2],
                0.0,
                'c2',
                !ReLU { },
                'max',
                !GlorotWeightInit { }
            ]],
            ['flat', [1024, 0.5, 'f1', !ReLU { }, !GlorotWeightInit { }]],
            ['flat', [1024, 0.5, 'f2', !ReLU { }, !GlorotWeightInit { }]]
          ]
n_in: 841
n_out: 10
