---
save_images: false
detailed_stats: false
dataset: /local/mnist.pkl.gz
pickled: true
random_seed: 42
L1_reg: 0.0
L2_reg: 0.0
n_epochs: 60
pretraining: !!null 
pretraining_passes: 5
training_method: normal
batch_size: 128
output_layer_options: { batch_normalization: true }
update_input: true
shuffle_dataset: true
cost_function: !NegLogLikelihood { }
learning_rate: !MultiplicativeDecayLearningRate { start: 1.0e-3, stop: 1.0e-7, multiplier: 0.85}
update_rule: !Adam { }
n_hidden: [
    ['flat',
        [2500,0.5,'h0',!ReLU { },!UniformWeightInit { min_w: -0.05 , max_w: 0.05 }, { batch_normalization: true } ]],
    ['flat',
        [2000,0.5,'h1',!ReLU { },!UniformWeightInit { min_w: -0.05 , max_w: 0.05 }, { batch_normalization: true } ]],
    ['flat',
        [1500,0.5,'h2',!ReLU { },!UniformWeightInit { min_w: -0.05 , max_w: 0.05 }, { batch_normalization: true } ]],
    ['flat',
        [1000,0.5,'h3',!ReLU { },!UniformWeightInit { min_w: -0.05 , max_w: 0.05 }, { batch_normalization: true } ]],
    ['flat',
        [ 500,0.5,'h4',!ReLU { },!UniformWeightInit { min_w: -0.05 , max_w: 0.05 }, { batch_normalization: true } ]]
          ]
n_in: 784
n_out: 10
