---
save_images: false
detailed_stats: false
dataset: /local/cifar10/
pickled: false
random_seed: 42
L1_reg: 0.0
L2_reg: 0.0
n_epochs: 100
pretraining: !!null
pretraining_passes: 2
training_method: normal
learning_rate: !MultiplicativeDecayLearningRate { start: 1.0e-4, stop: 1.0e-5, multiplier: 0.9 }
update_rule: !UProp { eta_plus: 1.1, eta_minus: 0.9, momentum: 0.9 }
batch_size: 128
cost_function: !CrossEntropy { }
n_hidden: [
            #input_shape,filter_shape,pool_size,drop_this,name_this,activation_this
            #input_shape needs to be defined only for 1st layer
            #input_shape:  [levels,x,y]
            #filter_shape: [count,x,y]
            #pool_size: [x,y]
            ['conv', [
                [3,32,32],
                [64,2,2],
                [2,2],
                0.,
                'c1',
                !TanH { },
                'max',
                !GlorotWeightInit { }
            ]],
            ['conv', [
                !!null ,
                [128,4,4],
                [2,2],
                0.,
                'c2',
                !TanH { },
                'max',
                !GlorotWeightInit { }
            ]],
            ['conv', [
                !!null ,
                [256,5,5],
                [2,2],
                0.,
                'c3',
                !TanH { },
                'max',
                !GlorotWeightInit { }
            ]],
            ['flat', [4096, 0.5, 'f1', !ReLU { }, !GlorotWeightInit { } ]],
            ['flat', [2048, 0.5, 'f2', !ReLU { }, !GlorotWeightInit { } ]]
          ]
n_in: 3072
RGB: True
n_out: 10

#Ensemble params
resample_size: 40000
method: !Bagging {}
ensemble_size: 30
