---
save_images: false
detailed_stats: false
dataset: /local/mnist.pkl.gz
pickled: true
random_seed: 42
L1_reg: 0.0
L2_reg: 0.0
n_epochs: 50
pretraining: !!null 
pretraining_passes: 5
training_method: normal
batch_size: 256
cost_function: !NegLogLikelihood { }
learning_rate: !MultiplicativeDecayLearningRate { start: 1.0e-3, stop: 1.0e-7, multiplier: 0.9}
update_rule: !ARMSProp2 { }
n_hidden: [
            ['conv', [
                [1,28,28],
                [64,5,5],
                [2,2],
                0.0,
                'c1',
                !ReLU { },
                'max',
                !GlorotWeightInit { }
            ]],
            ['conv', [
                !!null ,
                [128,5,5],
                [2,2],
                0.0,
                'c2',
                !ReLU { },
                'max',
                !GlorotWeightInit { }
            ]],
            ['flat', [1024, 0.5, 'f1', !ReLU { }, !GlorotWeightInit { }]],
            ['flat', [1024, 0.5, 'f2', !ReLU { }, !GlorotWeightInit { }]]
          ]
n_in: 784
n_out: 10
